services:
  traefik:
    networks:
      - AuthFrontNet
      
  whoami:
    labels:
      - "traefik.http.routers.whoami.middlewares=authentik@file"

  auth-server:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=AuthFrontNet"
