services:
  traefik:
    networks:
      - AuthFrontNet
      
  whoami:
    depends_on: 
      - auth-server
    labels:
      - "traefik.http.routers.whoami.middlewares=authentik@file"

  auth-server:
    labels:
      - "traefik.enable=true"
