services:
  traefik:
    image: "docker.io/traefik:v3.1"
    container_name: "traefik"
    ports:
      - "8080:80"
      - "8443:443"
    env_file:
      - "${shrooTreafikDir}/.traefik.env"
    networks:
      - TraefikNet
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${shrooTreafikDir}/letsencrypt:/letsencrypt"
      - "${shrooTreafikDir}/traefik.yml:/etc/traefik/traefik.yml"
      - "${shrooTreafikDir}/dynamic:/dynamic"
      - "TraefikLogs:/var/log/traefik/"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  whoami:
    image: "docker.io/traefik/whoami"
    container_name: "whoami"
    networks:
      - TraefikNet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s   
    labels:
      - "traefik.enable=true"
      - "traefik.routers.whoami.middlewares=authentik@file

networks:
  TraefikNet:
    name: TraefikNet
    driver: bridge
    internal: false

volumes:
  TraefikLogs:
    driver: local
    driver_opts:
      type: none
      device: ${shrooTreafikLogDir}
      o: bind
