################################################################
# Global configuration
################################################################
[global]
  checkNewVersion = true
  sendAnonymousUsage = false


################################################################
# Entrypoints configuration
################################################################
[entryPoints]
  [entryPoints.web]
    address = ":80"
      [entryPoints.web.http]
        [entryPoints.web.http.redirections]
          [entryPoints.web.http.redirections.entryPoint]
            to = "websecure"
            scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    asDefault = true
      [entryPoints.websecure.http]
        [entryPoints.websecure.http.tls]
          certResolver = "letsencrypt"


################################################################
# Traefik logs configuration
################################################################
[accessLog]
  addInternals = true
  filePath = "/var/log/traefik/access.log"
  #bufferingSize = 100

[log]
  level = "DEBUG"
  filePath = "/var/log/traefik/traefik.log"
  format = "json"


################################################################
# API and dashboard configuration
################################################################
[api]
  insecure = false
  dashboard = true

################################################################
# Ping configuration
################################################################
[ping]
  entrypoint = "web"

################################################################
# Docker configuration backend
################################################################
[providers]  
  [providers.docker]
    exposedByDefault = false
    defaultRule = "Host(`{{ .ContainerName }}.{{env \"DOMAIN_NAME\"}}`)"

  [providers.file]
    directory = "/dynamic"
    watch = true

################################################################
# Let's Encrypt
################################################################
[certificatesresolvers.letsencrypt.acme]
  email = "fluky@bdi.brr"
  storage = "/letsencrypt/acme.json"
  preferredchain="ISRG Root X1"
  keytype="RSA4096"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]
